apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: threesixtyallround-web-cert
  namespace: threesixtyallround-web-ns
spec:
  dnsNames:
    - 360allround.com
  secretName: threesixtyallround-web-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer