apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: threesixtyallround-webcert
  namespace: default
spec:
  dnsNames:
    - 360allround.com
  secretName: threesixtyallround-webtls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer