apiVersion: apps/v1
kind: Deployment
metadata:
  name: threesixtyallround-web
  namespace: threesixtyallround-web-ns
  labels:
    app: threesixtyallround-web
spec:
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 0
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      app: threesixtyallround-web
  template:
    metadata:
      labels:
        app: threesixtyallround-web
    spec:
      containers:
      - name: threesixtyallround-web
        image: hlads/threesixtyallround
        imagePullPolicy: Always
        ports:
        - containerPort: 80