apiVersion: apps/v1
kind: Deployment
metadata:
  name: threesixtyallround-web
  labels:
    app: threesixtyallround-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: threesixtyallround-web
  template:
    metadata:
      labels:
        app: threesixtyallround-web
    spec:
      containers:
      - name: threesixtyallround-web
        image: kaijehenstra/threesixtyallround
        ports:
        - containerPort: 80