apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: threesixtyallround-webingress
spec:
  tls:
  - hosts:
    - 360allround.com
    secretName: threesixtyallround-webtls
  rules:
  - host: 360allround.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: threesixtyallround-webservice
            port:
              number: 80
