apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: threesixtyallround-wp-pv-claim
  labels:
    app: threesixtyallround-wp
  namespace: threesixtyallround-web-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi