apiVersion: v1
kind: Service
metadata:
  name: threesixtyallround-web-service
  namespace: threesixtyallround-web-ns
spec:
  selector:
    app: threesixtyallround-wp
  ports:
    - port: 80 # Default port for image